export {default as Login} from "./Login"
export {default as LogReg} from "./LogReg"
export {default as LogRegSub} from "./LogRegSub"
export {default as Register} from "./Register"
export {default as Paypal} from "./Paypal"
